version: '3'

volumes:
  data:
  logs:

services:
  node:
    build: .
    container_name: node
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/usr/app
      - logs:/usr/app/logs
    networks:
      - net
    deploy:
      restart_policy:
        condition: on-failure
    restart: always
  postgres:
    build: ./database
    container_name: app-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgres/data
    volumes:
      - data:/var/lib/postgres/data
    networks:
      - net
    restart: always
networks:
  net:
    driver: bridge